use crate::{
    ApprovalRequest, ApprovalResponse, ApprovedRepositoriesResponse, ApprovedRepositorySummary,
    CheckpointResponse, CommandResult, CreateRemoteAssignmentRequest, DiffResponse,
    EnrollWorkerRequest, EnrolledWorker, Envelope, EventCursor, EventPage, FindingsResponse,
    HistoryResponse, LocalCommand, LocalCommandResponse, MutationPreview, MutationResult,
    OrderedRunEvent, PROTOCOL_VERSION, ProductClientMessage, ProductCommand,
    ProductCommandResponse, ProductEvent, ProductEventPage, ProductIntakeItem, ProductModule,
    ProductPage, ProductProject, ProductServerMessage, ProductSnapshot, ProductSprint,
    ProductTicket, ProductTicketPriority, ProductUser, ProductWorker, ProductWorkflowState,
    ProductWorkspace, ProductWorkspaceRole, RecoveryAction, RecoveryResponse,
    RegisteredRepositorySummary, RemoteAssignment, ResponseEnvelope, ReviewCheckKind,
    ReviewCheckResult, ReviewCheckStatus, ReviewReport, RunArtifactSegmentMetadata,
    RunArtifactSegmentResponse, RunArtifactStream, RunArtifactSummary, RunArtifactsDeletedResponse,
    RunArtifactsResponse, RunCompletedResponse, RunSnapshot, RunStartedResponse, SemanticEventKind,
    StructuredError, WorkerClaimResponse, WorkerEventAck, WorkerEventRequest,
    WorkerHeartbeatRequest, WorktreeSnapshot,
};
use domain::{
    ActionKind, ActionProposal, ApprovalScope, Changeset, ChangesetMutationKind, ChangesetState,
    Checkpoint, ControlPlaneId, ExecutionTargetId, Finding, FindingState, ProviderKind,
    ProviderSelection, RelativePath, Run, RunKind, RunState, TicketRef, WorktreeState,
};
use ts_rs::TS;

pub fn declarations() -> String {
    let declarations = [
        exported_decl::<ControlPlaneId>(),
        exported_decl::<ExecutionTargetId>(),
        exported_decl::<RelativePath>(),
        exported_decl::<TicketRef>(),
        exported_decl::<ActionKind>(),
        exported_decl::<ActionProposal>(),
        exported_decl::<ApprovalScope>(),
        exported_decl::<ChangesetMutationKind>(),
        exported_decl::<ChangesetState>(),
        exported_decl::<RunKind>(),
        exported_decl::<RunState>(),
        exported_decl::<ProviderKind>(),
        exported_decl::<ProviderSelection>(),
        exported_decl::<WorktreeState>(),
        exported_decl::<FindingState>(),
        exported_decl::<ApprovedRepositorySummary>(),
        exported_decl::<ApprovedRepositoriesResponse>(),
        exported_decl::<RegisteredRepositorySummary>(),
        exported_decl::<WorktreeSnapshot>(),
        exported_decl::<Changeset>(),
        exported_decl::<Run>(),
        exported_decl::<Checkpoint>(),
        exported_decl::<Finding>(),
        exported_decl::<ProductWorkspaceRole>(),
        exported_decl::<ProductUser>(),
        exported_decl::<ProductWorkspace>(),
        exported_decl::<ProductProject>(),
        exported_decl::<ProductWorkflowState>(),
        exported_decl::<ProductTicketPriority>(),
        exported_decl::<ProductTicket>(),
        exported_decl::<ProductSprint>(),
        exported_decl::<ProductModule>(),
        exported_decl::<ProductPage>(),
        exported_decl::<ProductIntakeItem>(),
        exported_decl::<ProductSnapshot>(),
        exported_decl::<ProductCommand>(),
        exported_decl::<ProductCommandResponse>(),
        exported_decl::<ProductEvent>(),
        exported_decl::<ProductEventPage>(),
        exported_decl::<ProductClientMessage>(),
        exported_decl::<ProductServerMessage>(),
        exported_decl::<ProductWorker>(),
        exported_decl::<EnrollWorkerRequest>(),
        exported_decl::<EnrolledWorker>(),
        exported_decl::<WorkerHeartbeatRequest>(),
        exported_decl::<CreateRemoteAssignmentRequest>(),
        exported_decl::<RemoteAssignment>(),
        exported_decl::<WorkerClaimResponse>(),
        exported_decl::<WorkerEventRequest>(),
        exported_decl::<WorkerEventAck>(),
        exported_decl::<ReviewCheckKind>(),
        exported_decl::<ReviewCheckStatus>(),
        exported_decl::<ReviewCheckResult>(),
        exported_decl::<ReviewReport>(),
        exported_decl::<LocalCommand>(),
        exported_decl::<RunStartedResponse>(),
        exported_decl::<RunCompletedResponse>(),
        exported_decl::<LocalCommandResponse>(),
        exported_decl::<SemanticEventKind>(),
        exported_decl::<OrderedRunEvent>(),
        exported_decl::<EventCursor>(),
        exported_decl::<EventPage>(),
        exported_decl::<StructuredError>(),
        exported_decl::<ApprovalRequest>(),
        exported_decl::<ApprovalResponse>(),
        exported_decl::<CheckpointResponse>(),
        exported_decl::<DiffResponse>(),
        exported_decl::<RunSnapshot>(),
        exported_decl::<HistoryResponse>(),
        exported_decl::<FindingsResponse>(),
        exported_decl::<RecoveryAction>(),
        exported_decl::<RecoveryResponse>(),
        exported_decl::<RunArtifactStream>(),
        exported_decl::<RunArtifactSegmentMetadata>(),
        exported_decl::<RunArtifactSummary>(),
        exported_decl::<RunArtifactsResponse>(),
        exported_decl::<RunArtifactSegmentResponse>(),
        exported_decl::<RunArtifactsDeletedResponse>(),
        exported_decl::<MutationPreview>(),
        exported_decl::<MutationResult>(),
        exported_decl::<Envelope<LocalCommand>>(),
        exported_decl::<CommandResult<LocalCommandResponse>>(),
        exported_decl::<ResponseEnvelope<LocalCommandResponse>>(),
    ];

    format!(
        "// This file is generated by `cargo run -p protocol --bin generate-types`.\n// Do not edit it directly.\n\nexport const PROTOCOL_VERSION = {PROTOCOL_VERSION:?} as const;\n\nexport type Id = string;\n\n{}\n",
        declarations.join("\n\n")
    )
}

fn exported_decl<T: TS>() -> String {
    format!("export {}", T::decl())
}
