use crate::{
    ApprovalRequest, ApprovalResponse, CheckpointResponse, CommandResult, DiffResponse, Envelope,
    EventCursor, EventPage, FindingsResponse, HistoryResponse, LocalCommand, LocalCommandResponse,
    MutationPreview, MutationResult, OrderedRunEvent, PROTOCOL_VERSION, RecoveryAction,
    RecoveryResponse, ResponseEnvelope, RunArtifactSegmentMetadata, RunArtifactSegmentResponse,
    RunArtifactStream, RunArtifactSummary, RunArtifactsDeletedResponse, RunArtifactsResponse,
    RunCompletedResponse, RunSnapshot, RunStartedResponse, SemanticEventKind, StructuredError,
};
use domain::{
    ActionKind, ActionProposal, ApprovalScope, Changeset, ChangesetMutationKind, ChangesetState,
    Checkpoint, ControlPlaneId, ExecutionTargetId, Finding, FindingState, RelativePath, Repository,
    Run, RunKind, RunState, TicketRef, Worktree, WorktreeState,
};
use ts_rs::TS;

pub fn declarations() -> String {
    let declarations = [
        exported_decl::<ControlPlaneId>(),
        exported_decl::<ExecutionTargetId>(),
        exported_decl::<RelativePath>(),
        exported_decl::<TicketRef>(),
        exported_decl::<ActionKind>(),
        exported_decl::<ActionProposal>(),
        exported_decl::<ApprovalScope>(),
        exported_decl::<ChangesetMutationKind>(),
        exported_decl::<ChangesetState>(),
        exported_decl::<RunKind>(),
        exported_decl::<RunState>(),
        exported_decl::<WorktreeState>(),
        exported_decl::<FindingState>(),
        exported_decl::<Repository>(),
        exported_decl::<Changeset>(),
        exported_decl::<Run>(),
        exported_decl::<Worktree>(),
        exported_decl::<Checkpoint>(),
        exported_decl::<Finding>(),
        exported_decl::<LocalCommand>(),
        exported_decl::<RunStartedResponse>(),
        exported_decl::<RunCompletedResponse>(),
        exported_decl::<LocalCommandResponse>(),
        exported_decl::<SemanticEventKind>(),
        exported_decl::<OrderedRunEvent>(),
        exported_decl::<EventCursor>(),
        exported_decl::<EventPage>(),
        exported_decl::<StructuredError>(),
        exported_decl::<ApprovalRequest>(),
        exported_decl::<ApprovalResponse>(),
        exported_decl::<CheckpointResponse>(),
        exported_decl::<DiffResponse>(),
        exported_decl::<RunSnapshot>(),
        exported_decl::<HistoryResponse>(),
        exported_decl::<FindingsResponse>(),
        exported_decl::<RecoveryAction>(),
        exported_decl::<RecoveryResponse>(),
        exported_decl::<RunArtifactStream>(),
        exported_decl::<RunArtifactSegmentMetadata>(),
        exported_decl::<RunArtifactSummary>(),
        exported_decl::<RunArtifactsResponse>(),
        exported_decl::<RunArtifactSegmentResponse>(),
        exported_decl::<RunArtifactsDeletedResponse>(),
        exported_decl::<MutationPreview>(),
        exported_decl::<MutationResult>(),
        exported_decl::<Envelope<LocalCommand>>(),
        exported_decl::<CommandResult<LocalCommandResponse>>(),
        exported_decl::<ResponseEnvelope<LocalCommandResponse>>(),
    ];

    format!(
        "// This file is generated by `cargo run -p protocol --bin generate-types`.\n// Do not edit it directly.\n\nexport const PROTOCOL_VERSION = {PROTOCOL_VERSION:?} as const;\n\nexport type Id = string;\n\n{}\n",
        declarations.join("\n\n")
    )
}

fn exported_decl<T: TS>() -> String {
    format!("export {}", T::decl())
}
