// This file is generated by `cargo run -p protocol --bin generate-types`.
// Do not edit it directly.

export const PROTOCOL_VERSION = "0.8" as const;

export type Id = string;

export type ControlPlaneId = string;

export type ExecutionTargetId = string;

export type RelativePath = string;

export type TicketRef = { control_plane_id: ControlPlaneId | null, workspace_id: string, project_id: string, ticket_id: string, identifier: string | null, title: string | null, };

export type ActionKind = "write_file";

export type ActionProposal = { action: ActionKind, target_path: RelativePath, content_sha256: string, };

export type ApprovalScope = { repository_id: string, changeset_id: string, base_sha: string, head_sha: string, proposal: ActionProposal, expires_at_unix_ms: number, };

export type ChangesetMutationKind = "commit" | "discard";

export type ChangesetState = "created" | "active" | "recoverable" | "reviewable" | "committed" | "discarded" | "failed" | "divergent";

export type RunKind = "mutation" | "read_only_review" | "precheck";

export type RunState = "queued" | "starting" | "running" | "awaiting_approval" | "reviewable" | "completed" | "interrupted" | "failed";

export type ProviderKind = "mock" | "claude-code" | "codex" | "opencode";

export type ProviderSelection = { kind: ProviderKind, model: string | null, };

export type WorktreeState = "creating" | "ready" | "removing" | "removed" | "failed" | "quarantined";

export type FindingState = "open" | "resolved" | "dismissed" | "superseded";

export type ApprovedRepositorySummary = { id: string, display_name: string, };

export type ApprovedRepositoriesResponse = { repositories: Array<ApprovedRepositorySummary>, };

export type RegisteredRepositorySummary = { id: string, default_branch: string, base_sha: string, version: number, };

export type WorktreeSnapshot = { id: string, changeset_id: string, base_sha: string, state: WorktreeState, version: number, };

export type Changeset = { id: string, repository_id: string, base_sha: string, head_sha: string, state: ChangesetState, ticket: TicketRef | null, version: number, };

export type Run = { id: string, changeset_id: string, state: RunState, proposal_digest: string | null, kind: RunKind, provider_selection: ProviderSelection | null, version: number, };

export type Checkpoint = { id: string, run_id: string, base_sha: string, head_sha: string, diff: string, };

export type Finding = { id: string, changeset_id: string, path: RelativePath | null, blob_identity: string, line_range: [number, number] | null, category: string, severity: string, message: string, evidence: string, state: FindingState, version: number, };

export type ReviewCheckKind = "format" | "typecheck" | "test" | "secret_scan" | "dependency_audit";

export type ReviewCheckStatus = "passed" | "failed" | "unavailable" | "timed_out" | "mutated";

export type ReviewCheckResult = { kind: ReviewCheckKind, status: ReviewCheckStatus, evidence: string, };

export type ReviewReport = { changeset_id: string, changeset_version: number, head_sha: string, changed_paths: Array<RelativePath>, unified_diff: string, checks: Array<ReviewCheckResult>, findings: Array<Finding>, };

export type LocalCommand = { "type": "list_approved_repositories" } | { "type": "register_repository", "data": { approved_repository_id: string, } } | { "type": "create_changeset", "data": { repository_id: string, base_sha: string, ticket: TicketRef | null, } } | { "type": "start_run", "data": { changeset_id: string, } } | { "type": "interrupt_run", "data": { run_id: string, } } | { "type": "respond_to_approval", "data": { run_id: string, scope: ApprovalScope, approved: boolean, } } | { "type": "get_checkpoint", "data": { run_id: string, } } | { "type": "get_diff", "data": { changeset_id: string, } } | { "type": "get_events", "data": { run_id: string, after_sequence: number, limit: number, } } | { "type": "get_snapshot", "data": { run_id: string, } } | { "type": "get_history", "data": { changeset_id: string, limit: number, } } | { "type": "get_recovery" } | { "type": "get_findings", "data": { changeset_id: string, } } | { "type": "review_changeset", "data": { changeset_id: string, expected_version: number, expected_head_sha: string, checks: Array<ReviewCheckKind>, } } | { "type": "get_run_artifacts", "data": { run_id: string, } } | { "type": "read_run_artifact_segment", "data": { run_id: string, artifact_id: string, segment_sequence: number, } } | { "type": "delete_run_artifacts", "data": { run_id: string, } } | { "type": "preview_commit", "data": { changeset_id: string, expected_version: number, expected_head_sha: string, } } | { "type": "commit_changeset", "data": { changeset_id: string, expected_version: number, expected_head_sha: string, confirmation_digest: string, } } | { "type": "preview_discard", "data": { changeset_id: string, expected_version: number, expected_head_sha: string, } } | { "type": "discard_changeset", "data": { changeset_id: string, expected_version: number, expected_head_sha: string, confirmation_digest: string, } };

export type RunStartedResponse = { run_id: string, changeset_id: string, worktree_id: string, approval_id: string | null, approval_request: ApprovalRequest | null, };

export type RunCompletedResponse = { run: Run, changeset: Changeset, checkpoint: Checkpoint, };

export type LocalCommandResponse = { "type": "approved_repositories", "data": ApprovedRepositoriesResponse } | { "type": "repository_registered", "data": RegisteredRepositorySummary } | { "type": "changeset_created", "data": Changeset } | { "type": "run_started", "data": RunStartedResponse } | { "type": "run_interrupted", "data": Run } | { "type": "approval_rejected", "data": Run } | { "type": "run_completed", "data": RunCompletedResponse } | { "type": "checkpoint", "data": CheckpointResponse } | { "type": "diff", "data": DiffResponse } | { "type": "events", "data": EventPage } | { "type": "snapshot", "data": RunSnapshot } | { "type": "history", "data": HistoryResponse } | { "type": "recovery", "data": RecoveryResponse } | { "type": "findings", "data": FindingsResponse } | { "type": "review_completed", "data": ReviewReport } | { "type": "run_artifacts", "data": RunArtifactsResponse } | { "type": "run_artifact_segment", "data": RunArtifactSegmentResponse } | { "type": "run_artifacts_deleted", "data": RunArtifactsDeletedResponse } | { "type": "mutation_preview", "data": MutationPreview } | { "type": "mutation_completed", "data": MutationResult };

export type SemanticEventKind = { "type": "text", "data": { text: string, } } | { "type": "action_proposal", "data": { proposal: ActionProposal, digest: string, } } | { "type": "action_result", "data": { digest: string, success: boolean, } } | { "type": "file_change", "data": { path: RelativePath, } } | { "type": "approval", "data": { digest: string, approved: boolean, } } | { "type": "lifecycle", "data": { state: RunState, } };

export type OrderedRunEvent = { run_id: string, sequence: number, event: SemanticEventKind, };

export type EventCursor = { run_id: string, after_sequence: number, };

export type EventPage = { events: Array<OrderedRunEvent>, next_cursor: EventCursor, };

export type StructuredError = { code: string, message: string, retryable: boolean, };

export type ApprovalRequest = { run_id: string, scope: ApprovalScope, digest: string, };

export type ApprovalResponse = { run_id: string, digest: string, approved: boolean, };

export type CheckpointResponse = { checkpoint: Checkpoint, };

export type DiffResponse = { changeset_id: string, unified_diff: string, };

export type RunSnapshot = { repository: RegisteredRepositorySummary, changeset: Changeset, run: Run, worktree: WorktreeSnapshot | null, checkpoint: Checkpoint | null, pending_approval: ApprovalRequest | null, findings: Array<Finding>, events: Array<OrderedRunEvent>, };

export type HistoryResponse = { changeset_id: string, runs: Array<Run>, };

export type FindingsResponse = { changeset_id: string, findings: Array<Finding>, };

export type RecoveryAction = { aggregate_kind: string, aggregate_id: string, action: string, detail: string, };

export type RecoveryResponse = { actions: Array<RecoveryAction>, };

export type RunArtifactStream = "stdout" | "stderr";

export type RunArtifactSegmentMetadata = { sequence: number, stored_bytes: number, sha256: string, };

export type RunArtifactSummary = { artifact_id: string, changeset_id: string, run_id: string, supervision_id: string, stream: RunArtifactStream, source_bytes: number, stored_bytes: number, segments: Array<RunArtifactSegmentMetadata>, sha256: string, redacted: boolean, process_truncated: boolean, quota_limited: boolean, created_at_unix_ms: number, updated_at_unix_ms: number, expires_at_unix_ms: number, };

export type RunArtifactsResponse = { run_id: string, artifacts: Array<RunArtifactSummary>, };

export type RunArtifactSegmentResponse = { run_id: string, artifact_id: string, stream: RunArtifactStream, segment: RunArtifactSegmentMetadata, artifact_sha256: string, content_base64: string, };

export type RunArtifactsDeletedResponse = { run_id: string, deleted_count: number, };

export type MutationPreview = { kind: ChangesetMutationKind, changeset_id: string, checkpoint_id: string, expected_version: number, expected_head_sha: string, manifest_sha256: string, confirmation_digest: string, };

export type MutationResult = { "kind": "commit", confirmation_digest: string, checkpoint_id: string, manifest_sha256: string, changeset: Changeset, worktree_state: WorktreeState, resulting_head_sha: string, app_ref: string, } | { "kind": "discard", confirmation_digest: string, checkpoint_id: string, manifest_sha256: string, changeset: Changeset, worktree_state: WorktreeState, };

export type Envelope<T> = { version: typeof PROTOCOL_VERSION, request_id: string, payload: T, };

export type CommandResult<T> = { "status": "ok", "data": T } | { "status": "error", "data": StructuredError };

export type ResponseEnvelope<T> = { version: typeof PROTOCOL_VERSION, request_id: string, result: CommandResult<T>, };
