// This file is generated by `cargo run -p protocol --bin generate-types`.
// Do not edit it directly.

export const PROTOCOL_VERSION = "0.2" as const;

export type Id = string;

export type ControlPlaneId = string;

export type ExecutionTargetId = string;

export type RelativePath = string;

export type TicketRef = { control_plane_id: ControlPlaneId | null, workspace_id: string, project_id: string, ticket_id: string, identifier: string | null, title: string | null, };

export type ActionKind = "write_file";

export type ActionProposal = { action: ActionKind, target_path: RelativePath, content_sha256: string, };

export type ApprovalScope = { repository_id: string, changeset_id: string, base_sha: string, head_sha: string, proposal: ActionProposal, expires_at_unix_ms: number, };

export type ChangesetState = "created" | "active" | "recoverable" | "reviewable" | "committed" | "discarded" | "failed" | "divergent";

export type RunKind = "mutation" | "read_only_review" | "precheck";

export type RunState = "queued" | "starting" | "running" | "awaiting_approval" | "reviewable" | "completed" | "interrupted" | "failed";

export type WorktreeState = "creating" | "ready" | "removing" | "removed" | "failed" | "quarantined";

export type FindingState = "open" | "resolved" | "dismissed" | "superseded";

export type Repository = { id: string, canonical_path: string, filesystem_identity: string, git_directory_identity: string, identity: string, primary_remote: string | null, default_branch: string, base_sha: string, version: number, };

export type Changeset = { id: string, repository_id: string, base_sha: string, head_sha: string, state: ChangesetState, ticket: TicketRef | null, version: number, };

export type Run = { id: string, changeset_id: string, state: RunState, proposal_digest: string | null, kind: RunKind, version: number, };

export type Worktree = { id: string, changeset_id: string, path: string, filesystem_identity: string, base_sha: string, state: WorktreeState, version: number, };

export type Checkpoint = { id: string, run_id: string, base_sha: string, head_sha: string, diff: string, };

export type Finding = { id: string, changeset_id: string, path: RelativePath | null, blob_identity: string, line_range: [number, number] | null, category: string, severity: string, message: string, evidence: string, state: FindingState, version: number, };

export type LocalCommand = { "type": "register_repository", "data": { path: string, } } | { "type": "create_changeset", "data": { repository_id: string, base_sha: string, ticket: TicketRef | null, } } | { "type": "start_run", "data": { changeset_id: string, } } | { "type": "interrupt_run", "data": { run_id: string, } } | { "type": "respond_to_approval", "data": { run_id: string, scope: ApprovalScope, approved: boolean, } } | { "type": "get_checkpoint", "data": { run_id: string, } } | { "type": "get_diff", "data": { changeset_id: string, } } | { "type": "get_events", "data": { run_id: string, after_sequence: number, limit: number, } } | { "type": "get_snapshot", "data": { run_id: string, } } | { "type": "get_history", "data": { changeset_id: string, limit: number, } } | { "type": "get_recovery" } | { "type": "get_findings", "data": { changeset_id: string, } } | { "type": "preview_commit", "data": { changeset_id: string, expected_version: number, expected_head_sha: string, } } | { "type": "commit_changeset", "data": { changeset_id: string, expected_version: number, expected_head_sha: string, confirmation_digest: string, } } | { "type": "preview_discard", "data": { changeset_id: string, expected_version: number, expected_head_sha: string, } } | { "type": "discard_changeset", "data": { changeset_id: string, expected_version: number, expected_head_sha: string, confirmation_digest: string, } };

export type RunStartedResponse = { run_id: string, changeset_id: string, worktree_id: string, approval_id: string, approval_request: ApprovalRequest, };

export type RunCompletedResponse = { run: Run, changeset: Changeset, checkpoint: Checkpoint, };

export type LocalCommandResponse = { "type": "repository_registered", "data": Repository } | { "type": "changeset_created", "data": Changeset } | { "type": "run_started", "data": RunStartedResponse } | { "type": "run_interrupted", "data": Run } | { "type": "approval_rejected", "data": Run } | { "type": "run_completed", "data": RunCompletedResponse } | { "type": "checkpoint", "data": CheckpointResponse } | { "type": "diff", "data": DiffResponse } | { "type": "events", "data": EventPage } | { "type": "snapshot", "data": RunSnapshot } | { "type": "history", "data": HistoryResponse } | { "type": "recovery", "data": RecoveryResponse } | { "type": "findings", "data": FindingsResponse } | { "type": "mutation_preview", "data": MutationPreview };

export type SemanticEventKind = { "type": "text", "data": { text: string, } } | { "type": "action_proposal", "data": { proposal: ActionProposal, digest: string, } } | { "type": "action_result", "data": { digest: string, success: boolean, } } | { "type": "file_change", "data": { path: RelativePath, } } | { "type": "approval", "data": { digest: string, approved: boolean, } } | { "type": "lifecycle", "data": { state: RunState, } };

export type OrderedRunEvent = { run_id: string, sequence: number, event: SemanticEventKind, };

export type EventCursor = { run_id: string, after_sequence: number, };

export type EventPage = { events: Array<OrderedRunEvent>, next_cursor: EventCursor, };

export type StructuredError = { code: string, message: string, retryable: boolean, };

export type ApprovalRequest = { run_id: string, scope: ApprovalScope, digest: string, };

export type ApprovalResponse = { run_id: string, digest: string, approved: boolean, };

export type CheckpointResponse = { checkpoint: Checkpoint, };

export type DiffResponse = { changeset_id: string, unified_diff: string, };

export type RunSnapshot = { repository: Repository, changeset: Changeset, run: Run, worktree: Worktree | null, checkpoint: Checkpoint | null, findings: Array<Finding>, events: Array<OrderedRunEvent>, };

export type HistoryResponse = { changeset_id: string, runs: Array<Run>, };

export type FindingsResponse = { changeset_id: string, findings: Array<Finding>, };

export type RecoveryAction = { aggregate_kind: string, aggregate_id: string, action: string, detail: string, };

export type RecoveryResponse = { actions: Array<RecoveryAction>, };

export type MutationPreview = { changeset_id: string, expected_version: number, expected_head_sha: string, confirmation_digest: string, };

export type Envelope<T> = { version: typeof PROTOCOL_VERSION, request_id: string, payload: T, };

export type CommandResult<T> = { "status": "ok", "data": T } | { "status": "error", "data": StructuredError };

export type ResponseEnvelope<T> = { version: typeof PROTOCOL_VERSION, request_id: string, result: CommandResult<T>, };
